export const soundRequires: {[key: string]: string} = {
  ate: require('../assets/voices/ate.mp3'),
  'be (am, is, are)': require('../assets/voices/be(am,is,are).mp3'),
  bear: require('../assets/voices/bear.mp3'),
  beat: require('../assets/voices/beat.mp3'),
  beaten: require('../assets/voices/beaten.mp3'),
  became: require('../assets/voices/became.mp3'),
  become: require('../assets/voices/become.mp3'),
  been: require('../assets/voices/been.mp3'),
  began: require('../assets/voices/began.mp3'),
  beget: require('../assets/voices/beget.mp3'),
  begin: require('../assets/voices/begin.mp3'),
  begot: require('../assets/voices/begot.mp3'),
  begotten: require('../assets/voices/begotten.mp3'),
  begun: require('../assets/voices/begun.mp3'),
  bend: require('../assets/voices/bend.mp3'),
  bent: require('../assets/voices/bent.mp3'),
  bereave: require('../assets/voices/bereave.mp3'),
  'bereft, bereaved': require('../assets/voices/bereft,bereaved.mp3'),
  beseech: require('../assets/voices/beseech.mp3'),
  'besought, beseeched': require('../assets/voices/besought,beseeched.mp3'),
  bet: require('../assets/voices/bet.mp3'),
  'bidden, bided': require('../assets/voices/bidden,bided.mp3'),
  bide: require('../assets/voices/bide.mp3'),
  bid: require('../assets/voices/bid.mp3'),
  bind: require('../assets/voices/bind.mp3'),
  bit: require('../assets/voices/bit.mp3'),
  bite: require('../assets/voices/bite.mp3'),
  bitten: require('../assets/voices/bitten.mp3'),
  bled: require('../assets/voices/bled.mp3'),
  bleed: require('../assets/voices/bleed.mp3'),
  blew: require('../assets/voices/blew.mp3'),
  blow: require('../assets/voices/blow.mp3'),
  blown: require('../assets/voices/blown.mp3'),
  'bode, bided': require('../assets/voices/bode,bided.mp3'),
  bore: require('../assets/voices/bore.mp3'),
  'born, borne': require('../assets/voices/born,borne.mp3'),
  bought: require('../assets/voices/bought.mp3'),
  bound: require('../assets/voices/bound.mp3'),
  break: require('../assets/voices/break.mp3'),
  bred: require('../assets/voices/bred.mp3'),
  breed: require('../assets/voices/breed.mp3'),
  bring: require('../assets/voices/bring.mp3'),
  'broadcast, broadcasted': require('../assets/voices/broadcast,broadcasted.mp3'),
  broadcast: require('../assets/voices/broadcast.mp3'),
  broke: require('../assets/voices/broke.mp3'),
  broken: require('../assets/voices/broken.mp3'),
  brought: require('../assets/voices/brought.mp3'),
  build: require('../assets/voices/build.mp3'),
  built: require('../assets/voices/built.mp3'),
  burn: require('../assets/voices/burn.mp3'),
  'burnt, burned': require('../assets/voices/burnt,burned.mp3'),
  burst: require('../assets/voices/burst.mp3'),
  'bust, busted': require('../assets/voices/bust,busted.mp3'),
  bust: require('../assets/voices/bust.mp3'),
  buy: require('../assets/voices/buy.mp3'),
  came: require('../assets/voices/came.mp3'),
  cast: require('../assets/voices/cast.mp3'),
  catch: require('../assets/voices/catch.mp3'),
  caught: require('../assets/voices/caught.mp3'),
  'chid, chided': require('../assets/voices/chid,chided.mp3'),
  'chidden, chided, chid': require('../assets/voices/chidden,chided,chid.mp3'),
  choose: require('../assets/voices/choose.mp3'),
  chose: require('../assets/voices/chose.mp3'),
  chosen: require('../assets/voices/chosen.mp3'),
  'clad, clothed': require('../assets/voices/clad,clothed.mp3'),
  clad: require('../assets/voices/clad.mp3'),
  clap: require('../assets/voices/clap.mp3'),
  'clapt, clapped': require('../assets/voices/clapt,clapped.mp3'),
  cleave: require('../assets/voices/cleave.mp3'),
  'cleft, cleaved': require('../assets/voices/cleft,cleaved.mp3'),
  cling: require('../assets/voices/cling.mp3'),
  clothe: require('../assets/voices/clothe.mp3'),
  'cloven, cleaved': require('../assets/voices/cloven,cleaved.mp3'),
  clung: require('../assets/voices/clung.mp3'),
  come: require('../assets/voices/come.mp3'),
  cost: require('../assets/voices/cost.mp3'),
  creep: require('../assets/voices/creep.mp3'),
  'crept, crope': require('../assets/voices/crept,crope.mp3'),
  'crept, cropen': require('../assets/voices/crept,cropen.mp3'),
  'crew, crowed': require('../assets/voices/crew,crowed.mp3'),
  crow: require('../assets/voices/crow.mp3'),
  'crown, crowed': require('../assets/voices/crown,crowed.mp3'),
  cut: require('../assets/voices/cut.mp3'),
  dare: require('../assets/voices/dare.mp3'),
  deal: require('../assets/voices/deal.mp3'),
  dealt: require('../assets/voices/dealt.mp3'),
  did: require('../assets/voices/did.mp3'),
  dig: require('../assets/voices/dig.mp3'),
  dive: require('../assets/voices/dive.mp3'),
  do: require('../assets/voices/do.mp3'),
  done: require('../assets/voices/done.mp3'),
  'dove, dived': require('../assets/voices/dove,dived.mp3'),
  drag: require('../assets/voices/drag.mp3'),
  drank: require('../assets/voices/drank.mp3'),
  draw: require('../assets/voices/draw.mp3'),
  drawn: require('../assets/voices/drawn.mp3'),
  dream: require('../assets/voices/dream.mp3'),
  'dreamt, dreamed': require('../assets/voices/dreamt,dreamed.mp3'),
  dress: require('../assets/voices/dress.mp3'),
  'drest, dressed': require('../assets/voices/drest,dressed.mp3'),
  drew: require('../assets/voices/drew.mp3'),
  drink: require('../assets/voices/drink.mp3'),
  drive: require('../assets/voices/drive.mp3'),
  driven: require('../assets/voices/driven.mp3'),
  drove: require('../assets/voices/drove.mp3'),
  'drug, dragged': require('../assets/voices/drug,dragged.mp3'),
  drunk: require('../assets/voices/drunk.mp3'),
  dug: require('../assets/voices/dug.mp3'),
  'durst, dared': require('../assets/voices/durst,dared.mp3'),
  dwell: require('../assets/voices/dwell.mp3'),
  'dwelt, dwelled': require('../assets/voices/dwelt,dwelled.mp3'),
  eat: require('../assets/voices/eat.mp3'),
  eaten: require('../assets/voices/eaten.mp3'),
  fall: require('../assets/voices/fall.mp3'),
  fallen: require('../assets/voices/fallen.mp3'),
  fed: require('../assets/voices/fed.mp3'),
  feed: require('../assets/voices/feed.mp3'),
  feel: require('../assets/voices/feel.mp3'),
  fell: require('../assets/voices/fell.mp3'),
  felt: require('../assets/voices/felt.mp3'),
  fight: require('../assets/voices/fight.mp3'),
  find: require('../assets/voices/find.mp3'),
  'fit, fitted': require('../assets/voices/fit,fitted.mp3'),
  fit: require('../assets/voices/fit.mp3'),
  fled: require('../assets/voices/fled.mp3'),
  flee: require('../assets/voices/flee.mp3'),
  flew: require('../assets/voices/flew.mp3'),
  fling: require('../assets/voices/fling.mp3'),
  flown: require('../assets/voices/flown.mp3'),
  flung: require('../assets/voices/flung.mp3'),
  fly: require('../assets/voices/fly.mp3'),
  forbade: require('../assets/voices/forbade.mp3'),
  forbid: require('../assets/voices/forbid.mp3'),
  forbidden: require('../assets/voices/forbidden.mp3'),
  forgave: require('../assets/voices/forgave.mp3'),
  forget: require('../assets/voices/forget.mp3'),
  forgive: require('../assets/voices/forgive.mp3'),
  forgiven: require('../assets/voices/forgiven.mp3'),
  forgot: require('../assets/voices/forgot.mp3'),
  forgotten: require('../assets/voices/forgotten.mp3'),
  forsake: require('../assets/voices/forsake.mp3'),
  forsaken: require('../assets/voices/forsaken.mp3'),
  forsook: require('../assets/voices/forsook.mp3'),
  fought: require('../assets/voices/fought.mp3'),
  found: require('../assets/voices/found.mp3'),
  freeze: require('../assets/voices/freeze.mp3'),
  froze: require('../assets/voices/froze.mp3'),
  frozen: require('../assets/voices/frozen.mp3'),
  gave: require('../assets/voices/gave.mp3'),
  get: require('../assets/voices/get.mp3'),
  gild: require('../assets/voices/gild.mp3'),
  'gilt, gilded': require('../assets/voices/gilt,gilded.mp3'),
  gird: require('../assets/voices/gird.mp3'),
  'girt, girded': require('../assets/voices/girt,girded.mp3'),
  give: require('../assets/voices/give.mp3'),
  given: require('../assets/voices/given.mp3'),
  go: require('../assets/voices/go.mp3'),
  gone: require('../assets/voices/gone.mp3'),
  'got, gotten': require('../assets/voices/got,gotten.mp3'),
  got: require('../assets/voices/got.mp3'),
  grew: require('../assets/voices/grew.mp3'),
  grind: require('../assets/voices/grind.mp3'),
  'ground, grinded': require('../assets/voices/ground,grinded.mp3'),
  grow: require('../assets/voices/grow.mp3'),
  grown: require('../assets/voices/grown.mp3'),
  had: require('../assets/voices/had.mp3'),
  hang: require('../assets/voices/hang.mp3'),
  have: require('../assets/voices/have.mp3'),
  hear: require('../assets/voices/hear.mp3'),
  heard: require('../assets/voices/heard.mp3'),
  heave: require('../assets/voices/heave.mp3'),
  held: require('../assets/voices/held.mp3'),
  'hew, hewed': require('../assets/voices/hew,hewed.mp3'),
  hew: require('../assets/voices/hew.mp3'),
  'hewn, hewed': require('../assets/voices/hewn,hewed.mp3'),
  hid: require('../assets/voices/hid.mp3'),
  hidden: require('../assets/voices/hidden.mp3'),
  hide: require('../assets/voices/hide.mp3'),
  hit: require('../assets/voices/hit.mp3'),
  'hoist, hoisted': require('../assets/voices/hoist,hoisted.mp3'),
  hoist: require('../assets/voices/hoist.mp3'),
  hold: require('../assets/voices/hold.mp3'),
  'hove, heaved': require('../assets/voices/hove,heaved.mp3'),
  'hoven, heaved,hove': require('../assets/voices/hoven,heaved,hove.mp3'),
  hung: require('../assets/voices/hung.mp3'),
  hurt: require('../assets/voices/hurt.mp3'),
  keep: require('../assets/voices/keep.mp3'),
  ken: require('../assets/voices/ken.mp3'),
  'kent, kenned': require('../assets/voices/kent,kenned.mp3'),
  kept: require('../assets/voices/kept.mp3'),
  kneel: require('../assets/voices/kneel.mp3'),
  'knelt, kneeled': require('../assets/voices/knelt,kneeled.mp3'),
  knew: require('../assets/voices/knew.mp3'),
  'knit, knitted': require('../assets/voices/knit,knitted.mp3'),
  knit: require('../assets/voices/knit.mp3'),
  know: require('../assets/voices/know.mp3'),
  known: require('../assets/voices/known.mp3'),
  lade: require('../assets/voices/lade.mp3'),
  'laden, laded': require('../assets/voices/laden,laded.mp3'),
  laid: require('../assets/voices/laid.mp3'),
  lain: require('../assets/voices/lain.mp3'),
  lay: require('../assets/voices/lay.mp3'),
  lead: require('../assets/voices/lead.mp3'),
  lean: require('../assets/voices/lean.mp3'),
  'leant, leaned': require('../assets/voices/leant,leaned.mp3'),
  leap: require('../assets/voices/leap.mp3'),
  'leapt, leaped': require('../assets/voices/leapt,leaped.mp3'),
  learn: require('../assets/voices/learn.mp3'),
  'learnt, learned': require('../assets/voices/learnt,learned.mp3'),
  leave: require('../assets/voices/leave.mp3'),
  led: require('../assets/voices/led.mp3'),
  left: require('../assets/voices/left.mp3'),
  lend: require('../assets/voices/lend.mp3'),
  lent: require('../assets/voices/lent.mp3'),
  let: require('../assets/voices/let.mp3'),
  lie: require('../assets/voices/lie.mp3'),
  light: require('../assets/voices/light.mp3'),
  lit: require('../assets/voices/lit.mp3'),
  'lode, laded': require('../assets/voices/lode,laded.mp3'),
  lose: require('../assets/voices/lose.mp3'),
  lost: require('../assets/voices/lost.mp3'),
  made: require('../assets/voices/made.mp3'),
  make: require('../assets/voices/make.mp3'),
  mean: require('../assets/voices/mean.mp3'),
  meant: require('../assets/voices/meant.mp3'),
  meet: require('../assets/voices/meet.mp3'),
  melt: require('../assets/voices/melt.mp3'),
  met: require('../assets/voices/met.mp3'),
  'molt, molted': require('../assets/voices/molt,molted.mp3'),
  'molten, melted': require('../assets/voices/molten,melted.mp3'),
  mow: require('../assets/voices/mow.mp3'),
  mowed: require('../assets/voices/mowed.mp3'),
  'mown, mowed': require('../assets/voices/mown,mowed.mp3'),
  or: require('../assets/voices/or.mp3'),
  paid: require('../assets/voices/paid.mp3'),
  pay: require('../assets/voices/pay.mp3'),
  plead: require('../assets/voices/plead.mp3'),
  'pled, pleaded': require('../assets/voices/pled,pleaded.mp3'),
  prove: require('../assets/voices/prove.mp3'),
  proved: require('../assets/voices/proved.mp3'),
  'proven, proved': require('../assets/voices/proven,proved.mp3'),
  put: require('../assets/voices/put.mp3'),
  'quit, quitted': require('../assets/voices/quit,quitted.mp3'),
  quit: require('../assets/voices/quit.mp3'),
  ran: require('../assets/voices/ran.mp3'),
  rang: require('../assets/voices/rang.mp3'),
  read: require('../assets/voices/read.mp3'),
  read2: require('../assets/voices/read2.mp3'),
  rend: require('../assets/voices/rend.mp3'),
  rent: require('../assets/voices/rent.mp3'),
  'rid, ridded': require('../assets/voices/rid,ridded.mp3'),
  rid: require('../assets/voices/rid.mp3'),
  ridden: require('../assets/voices/ridden.mp3'),
  ride: require('../assets/voices/ride.mp3'),
  ring: require('../assets/voices/ring.mp3'),
  rise: require('../assets/voices/rise.mp3'),
  risen: require('../assets/voices/risen.mp3'),
  rive: require('../assets/voices/rive.mp3'),
  'riven, rived': require('../assets/voices/riven,rived.mp3'),
  rode: require('../assets/voices/rode.mp3'),
  rose: require('../assets/voices/rose.mp3'),
  'rove, rived': require('../assets/voices/rove,rived.mp3'),
  run: require('../assets/voices/run.mp3'),
  rung: require('../assets/voices/rung.mp3'),
  said: require('../assets/voices/said.mp3'),
  sang: require('../assets/voices/sang.mp3'),
  sank: require('../assets/voices/sank.mp3'),
  sat: require('../assets/voices/sat.mp3'),
  saw: require('../assets/voices/saw.mp3'),
  sawed: require('../assets/voices/sawed.mp3'),
  'sawn, sawed': require('../assets/voices/sawn,sawed.mp3'),
  say: require('../assets/voices/say.mp3'),
  see: require('../assets/voices/see.mp3'),
  seek: require('../assets/voices/seek.mp3'),
  seen: require('../assets/voices/seen.mp3'),
  seethe: require('../assets/voices/seethe.mp3'),
  sell: require('../assets/voices/sell.mp3'),
  send: require('../assets/voices/send.mp3'),
  sent: require('../assets/voices/sent.mp3'),
  set: require('../assets/voices/set.mp3'),
  sew: require('../assets/voices/sew.mp3'),
  sewed: require('../assets/voices/sewed.mp3'),
  'sewn, sewed, sewen': require('../assets/voices/sewn,sewed,sewen.mp3'),
  shake: require('../assets/voices/shake.mp3'),
  shaken: require('../assets/voices/shaken.mp3'),
  shave: require('../assets/voices/shave.mp3'),
  shaved: require('../assets/voices/shaved.mp3'),
  shaven: require('../assets/voices/shaven.mp3'),
  shear: require('../assets/voices/shear.mp3'),
  shed: require('../assets/voices/shed.mp3'),
  'shit, shat, shitted, shitten': require('../assets/voices/shit,shat,shitted,shitten.mp3'),
  'shit, shat, shitted': require('../assets/voices/shit,shat,shitted.mp3'),
  shit: require('../assets/voices/shit.mp3'),
  'shodden, shod, shoed': require('../assets/voices/shodden,shod,shoed.mp3'),
  'shoe, shoed': require('../assets/voices/shoe,shoed.mp3'),
  shoe: require('../assets/voices/shoe.mp3'),
  shook: require('../assets/voices/shook.mp3'),
  shoot: require('../assets/voices/shoot.mp3'),
  'shore, sheared': require('../assets/voices/shore,sheared.mp3'),
  'shorn, sheared': require('../assets/voices/shorn,sheared.mp3'),
  shot: require('../assets/voices/shot.mp3'),
  show: require('../assets/voices/show.mp3'),
  showed: require('../assets/voices/showed.mp3'),
  shown: require('../assets/voices/shown.mp3'),
  shrunk: require('../assets/voices/shrunk.mp3'),
  shut: require('../assets/voices/shut.mp3'),
  sing: require('../assets/voices/sing.mp3'),
  sink: require('../assets/voices/sink.mp3'),
  sit: require('../assets/voices/sit.mp3'),
  'slank, slunk, slinked': require('../assets/voices/slank,slunk,slinked.mp3'),
  sleep: require('../assets/voices/sleep.mp3'),
  slept: require('../assets/voices/slept.mp3'),
  slid: require('../assets/voices/slid.mp3'),
  'slidden, slid': require('../assets/voices/slidden,slid.mp3'),
  slide: require('../assets/voices/slide.mp3'),
  sling: require('../assets/voices/sling.mp3'),
  slink: require('../assets/voices/slink.mp3'),
  slip: require('../assets/voices/slip.mp3'),
  'slipt, slipped': require('../assets/voices/slipt,slipped.mp3'),
  slit: require('../assets/voices/slit.mp3'),
  slitten: require('../assets/voices/slitten.mp3'),
  slung: require('../assets/voices/slung.mp3'),
  'slunk, slinked, slank': require('../assets/voices/slunk,slinked,slank.mp3'),
  smell: require('../assets/voices/smell.mp3'),
  'smelt,smelled': require('../assets/voices/smelt,smelled.mp3'),
  smite: require('../assets/voices/smite.mp3'),
  'smitten, smitted': require('../assets/voices/smitten,smitted.mp3'),
  'smote, smit': require('../assets/voices/smote,smit.mp3'),
  'sod, seethed': require('../assets/voices/sod,seethed.mp3'),
  'sodden, seethed': require('../assets/voices/sodden,seethed.mp3'),
  sold: require('../assets/voices/sold.mp3'),
  sought: require('../assets/voices/sought.mp3'),
  sow: require('../assets/voices/sow.mp3'),
  sowed: require('../assets/voices/sowed.mp3'),
  'sown, sowed': require('../assets/voices/sown,sowed.mp3'),
  span: require('../assets/voices/span.mp3'),
  'spat, spit': require('../assets/voices/spat,spit.mp3'),
  speak: require('../assets/voices/speak.mp3'),
  spell: require('../assets/voices/spell.mp3'),
  'spelt, spelled': require('../assets/voices/spelt,spelled.mp3'),
  spend: require('../assets/voices/spend.mp3'),
  spent: require('../assets/voices/spent.mp3'),
  spill: require('../assets/voices/spill.mp3'),
  'spilt, spilled': require('../assets/voices/spilt,spilled.mp3'),
  spin: require('../assets/voices/spin.mp3'),
  spit: require('../assets/voices/spit.mp3'),
  split: require('../assets/voices/split.mp3'),
  spoke: require('../assets/voices/spoke.mp3'),
  spoken: require('../assets/voices/spoken.mp3'),
  sprang: require('../assets/voices/sprang.mp3'),
  'spread, spreaded': require('../assets/voices/spread,spreaded.mp3'),
  spread: require('../assets/voices/spread.mp3'),
  spring: require('../assets/voices/spring.mp3'),
  sprung: require('../assets/voices/sprung.mp3'),
  spun: require('../assets/voices/spun.mp3'),
  stand: require('../assets/voices/stand.mp3'),
  stang: require('../assets/voices/stang.mp3'),
  'stank, stunk': require('../assets/voices/stank,stunk.mp3'),
  steal: require('../assets/voices/steal.mp3'),
  stick: require('../assets/voices/stick.mp3'),
  sting: require('../assets/voices/sting.mp3'),
  stink: require('../assets/voices/stink.mp3'),
  stole: require('../assets/voices/stole.mp3'),
  stolen: require('../assets/voices/stolen.mp3'),
  stood: require('../assets/voices/stood.mp3'),
  'stove, staved': require('../assets/voices/stove,staved.mp3'),
  stove: require('../assets/voices/stove.mp3'),
  'stoven, stove, staved': require('../assets/voices/stoven,stove,staved.mp3'),
  'straught, straight, stretched': require('../assets/voices/straught,straight,stretched.mp3'),
  stretch: require('../assets/voices/stretch.mp3'),
  strew: require('../assets/voices/strew.mp3'),
  strewed: require('../assets/voices/strewed.mp3'),
  strewn: require('../assets/voices/strewn.mp3'),
  'stridden, strode, strid, stridded': require('../assets/voices/stridden,strode,strid,stridded.mp3'),
  stride: require('../assets/voices/stride.mp3'),
  strike: require('../assets/voices/strike.mp3'),
  string: require('../assets/voices/string.mp3'),
  strip: require('../assets/voices/strip.mp3'),
  'stript, stripped': require('../assets/voices/stript,stripped.mp3'),
  strive: require('../assets/voices/strive.mp3'),
  'striven, strived': require('../assets/voices/striven,strived.mp3'),
  'strode, strided': require('../assets/voices/strode,strided.mp3'),
  'strove, strived': require('../assets/voices/strove,strived.mp3'),
  'struck, stricken': require('../assets/voices/struck,stricken.mp3'),
  struck: require('../assets/voices/struck.mp3'),
  'strung, stringed': require('../assets/voices/strung,stringed.mp3'),
  'stuck, sticked': require('../assets/voices/stuck,sticked.mp3'),
  stung: require('../assets/voices/stung.mp3'),
  stunk: require('../assets/voices/stunk.mp3'),
  sung: require('../assets/voices/sung.mp3'),
  sunk: require('../assets/voices/sunk.mp3'),
  swam: require('../assets/voices/swam.mp3'),
  swang: require('../assets/voices/swang.mp3'),
  swear: require('../assets/voices/swear.mp3'),
  'sweat, sweated': require('../assets/voices/sweat,sweated.mp3'),
  sweat: require('../assets/voices/sweat.mp3'),
  sweep: require('../assets/voices/sweep.mp3'),
  'swelt, swelled': require('../assets/voices/swelt,swelled.mp3'),
  swelt: require('../assets/voices/swelt.mp3'),
  'swept, sweeped': require('../assets/voices/swept,sweeped.mp3'),
  swim: require('../assets/voices/swim.mp3'),
  swing: require('../assets/voices/swing.mp3'),
  'swollen, swelled': require('../assets/voices/swollen,swelled.mp3'),
  swore: require('../assets/voices/swore.mp3'),
  sworn: require('../assets/voices/sworn.mp3'),
  swum: require('../assets/voices/swum.mp3'),
  swung: require('../assets/voices/swung.mp3'),
  take: require('../assets/voices/take.mp3'),
  taken: require('../assets/voices/taken.mp3'),
  taught: require('../assets/voices/taught.mp3'),
  teach: require('../assets/voices/teach.mp3'),
  tear: require('../assets/voices/tear.mp3'),
  tell: require('../assets/voices/tell.mp3'),
  think: require('../assets/voices/think.mp3'),
  thought: require('../assets/voices/thought.mp3'),
  threw: require('../assets/voices/threw.mp3'),
  thrive: require('../assets/voices/thrive.mp3'),
  'thriven, thrived': require('../assets/voices/thriven,thrived.mp3'),
  'throve, thrived': require('../assets/voices/throve,thrived.mp3'),
  throw: require('../assets/voices/throw.mp3'),
  thrown: require('../assets/voices/thrown.mp3'),
  'thrust, thrusted': require('../assets/voices/thrust,thrusted.mp3'),
  thrust: require('../assets/voices/thrust.mp3'),
  told: require('../assets/voices/told.mp3'),
  took: require('../assets/voices/took.mp3'),
  tore: require('../assets/voices/tore.mp3'),
  torn: require('../assets/voices/torn.mp3'),
  understand: require('../assets/voices/understand.mp3'),
  understood: require('../assets/voices/understood.mp3'),
  vex: require('../assets/voices/vex.mp3'),
  'vext, vexed': require('../assets/voices/vext,vexed.mp3'),
  wake: require('../assets/voices/wake.mp3'),
  'was, were': require('../assets/voices/was,were.mp3'),
  wax: require('../assets/voices/wax.mp3'),
  'waxen, waxed': require('../assets/voices/waxen,waxed.mp3'),
  wear: require('../assets/voices/wear.mp3'),
  weave: require('../assets/voices/weave.mp3'),
  'wed, wedded': require('../assets/voices/wed,wedded.mp3'),
  wed: require('../assets/voices/wed.mp3'),
  weep: require('../assets/voices/weep.mp3'),
  wend: require('../assets/voices/wend.mp3'),
  'went, wended': require('../assets/voices/went,wended.mp3'),
  went: require('../assets/voices/went.mp3'),
  'wept, weeped': require('../assets/voices/wept,weeped.mp3'),
  'wet, wetted': require('../assets/voices/wet,wetted.mp3'),
  wet: require('../assets/voices/wet.mp3'),
  'wex, waxed': require('../assets/voices/wex,waxed.mp3'),
  win: require('../assets/voices/win.mp3'),
  wind: require('../assets/voices/wind.mp3'),
  woke: require('../assets/voices/woke.mp3'),
  woken: require('../assets/voices/woken.mp3'),
  won: require('../assets/voices/won.mp3'),
  wore: require('../assets/voices/wore.mp3'),
  worn: require('../assets/voices/worn.mp3'),
  wound: require('../assets/voices/wound.mp3'),
  wove: require('../assets/voices/wove.mp3'),
  woven: require('../assets/voices/woven.mp3'),
  'wrang, wrung, wringed': require('../assets/voices/wrang,wrung,wringed.mp3'),
  wreak: require('../assets/voices/wreak.mp3'),
  wring: require('../assets/voices/wring.mp3'),
  write: require('../assets/voices/write.mp3'),
  writhe: require('../assets/voices/writhe.mp3'),
  'writhen, writhed': require('../assets/voices/writhen,writhed.mp3'),
  written: require('../assets/voices/written.mp3'),
  'wroke, wreaked': require('../assets/voices/wroke,wreaked.mp3'),
  'wroken, wreaked': require('../assets/voices/wroken,wreaked.mp3'),
  wrote: require('../assets/voices/wrote.mp3'),
  'wrothe, writhed': require('../assets/voices/wrothe,writhed.mp3'),
  'wrung, wringed': require('../assets/voices/wrung,wringed.mp3'),
};
